name: 'LeanIX Release Docker Image'
description: 'Build, tag and push a docker image.'
inputs:
  path:
    description: 'Docker build context path, defaults to .'
    default: '.'
  name:
    description: 'Name of the image to build, defaults to name of the repository'
  dockerfile:
    description: 'Optional of to the dockerfile (-f parameter of docker build)'
  only-output-tags:
    description: 'Whether to only output current tag again, defaults to false'
    default: false
  registry:
    description: 'Whether to use docker-hub, acr or acr-public, defaults to docker-hub'
    default: 'docker-hub'
  enable-cache:
    description: 'Enable caching docker layers'
    default: true
  always-increment-version:
    description: 'Always increment the version number and create a new tag'
    default: false
outputs:
  tag:
    description: 'The tag that was build and pushed'
runs:
  using: 'node12'
  main: 'dist/index.js'