name: test

on: [push]

jobs:
  test:
    name: test-${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: use-action
      uses: ./
